name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch tags and master
      run: |
          git fetch --tags
          git branch --create-reflog master origin/master
          echo REF: $GITHUB_REF
          echo SHA: $GITHUB_SHA
          echo ::set-env name=GIT_BRANCH::$GITHUB_REF
    - name: Determine .net core version
      run: |
          echo .NET Core Version: `sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' src/global.json`
          echo ::set-env name=DOTNET_VERSION::`sed -n 's|.*"version":\s*"\([^"]*\)".*|\1|p' src/global.json`
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Setup Nuget
      run: sudo apt-get install nuget
    - name: Install Build Version Tool
      run: nuget install FunFair.BuildVersion -ExcludeVersion -Source ${{ secrets.FUNFAIR_NUGET_FEED }}
    - name: Set Define Build Version
      run: dotnet FunFair.BuildVersion/lib/BuildVersion.dll  ${{ steps.buildnumber.outputs.build_number }} 
    - name: Setup nuget
      run: sudo apt-get install nuget
    - name: Add personal feed
      run: sudo nuget sources add -name Credfeto -Source https://www.myget.org/F/credfeto/api/v3/index.json
    - name: Restore with dotnet
      run: |
         cd src
         dotnet restore --source https://www.myget.org/F/credfeto/api/v3/index.json --source https://api.nuget.org/v3/index.json
    - name: Build with dotnet
      run: |
         cd src
         dotnet build --configuration Release /p:Version=${{ env.BUILD_VERSION }} --no-restore
    - name: Publish OutputBuilderClient
      run: |
         cd src
         dotnet publish OutputBuilderClient --configuration Release -o ../prepublish/OutputBuilderClient/lib /p:Version=${{ env.BUILD_VERSION }} --no-restore --no-build
    - name: pack OutputBuilderClient tool
      run: nuget pack prepublish/OutputBuilderClient/package.nuspec -tool -outputdirectory dist -version ${{ env.BUILD_VERSION }}
    - name: Publish BuildSiteIndex
      run: |
         cd src
         dotnet publish BuildSiteIndex --configuration Release -o ../prepublish/BuildSiteIndex/lib /p:Version=${{ env.BUILD_VERSION }} --no-restore --no-build
    - name: pack BuildSiteIndex tool
      run: nuget pack prepublish/BuildSiteIndex/package.nuspec -tool -outputdirectory dist -version ${{ env.BUILD_VERSION }}
    - name: Publish DeleteImageIfCorrupt
      run: |
         cd src
         dotnet publish DeleteImageIfCorrupt --configuration Release -o ../prepublish/DeleteImageIfCorrupt.lib /p:Version=${{ env.BUILD_VERSION }} --no-restore --no-build  
    - name: pack DeleteImageIfCorrupt tool
      run: nuget pack prepublish/DeleteImageIfCorrupt/package.nuspec -tool -outputdirectory dist -version ${{ env.BUILD_VERSION }}
    - name: publish
      run: dotnet nuget push dist/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
