name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Fetch tags and master
      run: |
          git fetch --tags
          git branch --create-reflog master origin/master
          echo REF: $GITHUB_REF
          echo SHA: $GITHUB_SHA
          echo ::set-env name=GIT_BRANCH::$GITHUB_REF
    - name: Determine .net core version
      uses: credfeto/action-dotnet-version-detect@master
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v2
      with:
        token: ${{secrets.github_token}}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Install Build Version Tool
      run: |
        dotnet new tool-manifest
        dotnet tool install --local FunFair.BuildVersion --add-source ${{ secrets.FUNFAIR_NUGET_FEED }}
    - name: Set Define Build Version
      run: dotnet BuildVersion ${{ steps.buildnumber.outputs.build_number }} 
    - name: Restore with dotnet
      run: |
         cd src
         dotnet restore --source https://api.nuget.org/v3/index.json
    - name: Build with dotnet
      run: |
         cd src
         dotnet build --configuration Release /p:Version=${{ env.BUILD_VERSION }} --no-restore
    - name: Pack components
      run: |
         cd src
         dotnet pack --configuration Release /p:Version=${{ env.BUILD_VERSION }} --no-restore --output ../dist
    - name: publish
      run: |
        dotnet nuget push dist/Credfeto.Gallery.FileNaming.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.Image.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.ObjectModel.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.Scanner.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.Storage.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.Upload.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.UploadData.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.OutputBuilder.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.SiteIndexBuilder.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
        dotnet nuget push dist/Credfeto.Gallery.DeleteCorruptImage.*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_FEED }}
