name: Update packages

on:
  schedule:
  - cron: "* * * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1    
    - uses: fregante/setup-git-token@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      with:
        dotnet-version: 3.0.100
    - name: Setup nuget
      run: sudo apt-get install nuget
    - name: Add personal feed
      run: sudo nuget sources add -name Credfeto -Source https://www.myget.org/F/credfeto/api/v3/index.json
    - name: Look for new packages
      run: |
            mkdir .update
            cd .update
            nuget.exe install Credfeto.UpdatePackages -ExcludeVersion -Source https://www.myget.org/F/credfeto/api/v3/index.json
            cd ..
            dotnet .update\tools\Credfeto.UpdatePackages\lib\UpdatePackages.dll -folder "." -prefix "Microsoft.CodeAnalysis.FxCopAnalyzers"
            if [ $? -eq 0 ]
            then
                dotnet restore --source https://www.myget.org/F/credfeto/api/v3/index.json --source https://api.nuget.org/v3/index.json
                dotnet build --configuration Release --no-restore
            fi
